/// ISO 3166-1 alpha-3 → full country name lookup.
/// Focused on Interpol Yellow Notice nationalities — expanded as needed.
abstract final class CountryUtils {
  static String languageFromCode(String? code) {
    if (code == null || code.isEmpty) return code ?? '';
    const codes = {
      'ENG': 'English',
      'FRE': 'French',
      'SPA': 'Spanish',
      'POR': 'Portuguese',
      'GER': 'German',
      'ITA': 'Italian',
      'RUS': 'Russian',
      'ARA': 'Arabic',
      'CHI': 'Chinese',
      'JPN': 'Japanese',
      'KOR': 'Korean',
      'DUT': 'Dutch',
      'POL': 'Polish',
      'TUR': 'Turkish',
      'HIN': 'Hindi',
      'BEN': 'Bengali',
      'VIE': 'Vietnamese',
      'THA': 'Thai',
      'RUM': 'Romanian',
      'HUN': 'Hungarian',
      'CZE': 'Czech',
      'SWE': 'Swedish',
      'NOR': 'Norwegian',
      'DAN': 'Danish',
      'FIN': 'Finnish',
      'GRE': 'Greek',
      'HEB': 'Hebrew',
      'UKR': 'Ukrainian',
      'CAT': 'Catalan',
      'SRP': 'Serbian',
      'HRV': 'Croatian',
      'SLO': 'Slovak',
      'BUL': 'Bulgarian',
    };
    return codes[code.toUpperCase()] ?? nameFromAlpha3(code);
  }

  /// Resolves a country code to its full name.
  /// Accepts both ISO 3166-1 alpha-2 (e.g. "EC") and alpha-3 (e.g. "ECU").
  /// Falls back to the code itself if not found.
  static String nameFromAlpha3(String? code) {
    if (code == null || code.isEmpty) return code ?? '';
    final upper = code.toUpperCase().trim();
    // Try alpha-3 first
    if (upper.length == 3) return _alpha3ToName[upper] ?? upper;
    // Try alpha-2
    if (upper.length == 2) return _alpha2ToName[upper] ?? upper;
    return upper;
  }

  /// Resolves ISO 3166-1 alpha-2 code to full country name.
  static String nameFromAlpha2(String? code) {
    if (code == null || code.isEmpty) return code ?? '';
    final upper = code.toUpperCase().trim();
    return _alpha2ToName[upper] ?? nameFromAlpha3(upper);
  }

  static const Map<String, String> _alpha3ToName = {
    'AFG': 'Afghanistan', 'ALB': 'Albania', 'DZA': 'Algeria',
    'AGO': 'Angola', 'ARG': 'Argentina', 'ARM': 'Armenia',
    'AUS': 'Australia', 'AUT': 'Austria', 'AZE': 'Azerbaijan',
    'BHS': 'Bahamas', 'BHR': 'Bahrain', 'BGD': 'Bangladesh',
    'BLR': 'Belarus', 'BEL': 'Belgium', 'BLZ': 'Belize',
    'BEN': 'Benin', 'BOL': 'Bolivia', 'BIH': 'Bosnia and Herzegovina',
    'BWA': 'Botswana', 'BRA': 'Brazil', 'BGR': 'Bulgaria',
    'BFA': 'Burkina Faso', 'BDI': 'Burundi', 'CPV': 'Cape Verde',
    'KHM': 'Cambodia', 'CMR': 'Cameroon', 'CAN': 'Canada',
    'CAF': 'Central African Republic', 'TCD': 'Chad', 'CHL': 'Chile',
    'CHN': 'China', 'COL': 'Colombia', 'COM': 'Comoros',
    'COD': 'Congo (DRC)', 'COG': 'Congo', 'CRI': 'Costa Rica',
    'CIV': "Côte d'Ivoire", 'HRV': 'Croatia', 'CUB': 'Cuba',
    'CYP': 'Cyprus', 'CZE': 'Czech Republic', 'DNK': 'Denmark',
    'DJI': 'Djibouti', 'DOM': 'Dominican Republic', 'ECU': 'Ecuador',
    'EGY': 'Egypt', 'SLV': 'El Salvador', 'GNQ': 'Equatorial Guinea',
    'ERI': 'Eritrea', 'EST': 'Estonia', 'ETH': 'Ethiopia',
    'FJI': 'Fiji', 'FIN': 'Finland', 'FRA': 'France',
    'GAB': 'Gabon', 'GMB': 'Gambia', 'GEO': 'Georgia',
    'DEU': 'Germany', 'GHA': 'Ghana', 'GRC': 'Greece',
    'GTM': 'Guatemala', 'GIN': 'Guinea', 'GNB': 'Guinea-Bissau',
    'GUY': 'Guyana', 'HTI': 'Haiti', 'HND': 'Honduras',
    'HUN': 'Hungary', 'ISL': 'Iceland', 'IND': 'India',
    'IDN': 'Indonesia', 'IRN': 'Iran', 'IRQ': 'Iraq',
    'IRL': 'Ireland', 'ISR': 'Israel', 'ITA': 'Italy',
    'JAM': 'Jamaica', 'JPN': 'Japan', 'JOR': 'Jordan',
    'KAZ': 'Kazakhstan', 'KEN': 'Kenya', 'KWT': 'Kuwait',
    'KGZ': 'Kyrgyzstan', 'LAO': 'Laos', 'LVA': 'Latvia',
    'LBN': 'Lebanon', 'LBR': 'Liberia', 'LBY': 'Libya',
    'LTU': 'Lithuania', 'LUX': 'Luxembourg', 'MKD': 'North Macedonia',
    'MDG': 'Madagascar', 'MWI': 'Malawi', 'MYS': 'Malaysia',
    'MDV': 'Maldives', 'MLI': 'Mali', 'MLT': 'Malta',
    'MRT': 'Mauritania', 'MUS': 'Mauritius', 'MEX': 'Mexico',
    'MDA': 'Moldova', 'MNG': 'Mongolia', 'MNE': 'Montenegro',
    'MAR': 'Morocco', 'MOZ': 'Mozambique', 'MMR': 'Myanmar',
    'NAM': 'Namibia', 'NPL': 'Nepal', 'NLD': 'Netherlands',
    'NZL': 'New Zealand', 'NIC': 'Nicaragua', 'NER': 'Niger',
    'NGA': 'Nigeria', 'NOR': 'Norway', 'OMN': 'Oman',
    'PAK': 'Pakistan', 'PAN': 'Panama', 'PNG': 'Papua New Guinea',
    'PRY': 'Paraguay', 'PER': 'Peru', 'PHL': 'Philippines',
    'POL': 'Poland', 'PRT': 'Portugal', 'QAT': 'Qatar',
    'ROU': 'Romania', 'RUS': 'Russia', 'RWA': 'Rwanda',
    'SAU': 'Saudi Arabia', 'SEN': 'Senegal', 'SRB': 'Serbia',
    'SLE': 'Sierra Leone', 'SOM': 'Somalia', 'ZAF': 'South Africa',
    'SSD': 'South Sudan', 'ESP': 'Spain', 'LKA': 'Sri Lanka',
    'SDN': 'Sudan', 'SUR': 'Suriname', 'SWE': 'Sweden',
    'CHE': 'Switzerland', 'SYR': 'Syria', 'TWN': 'Taiwan',
    'TJK': 'Tajikistan', 'TZA': 'Tanzania', 'THA': 'Thailand',
    'TLS': 'Timor-Leste', 'TGO': 'Togo', 'TTO': 'Trinidad and Tobago',
    'TUN': 'Tunisia', 'TUR': 'Turkey', 'TKM': 'Turkmenistan',
    'UGA': 'Uganda', 'UKR': 'Ukraine', 'ARE': 'United Arab Emirates',
    'GBR': 'United Kingdom', 'USA': 'United States',
    'URY': 'Uruguay', 'UZB': 'Uzbekistan', 'VEN': 'Venezuela',
    'VNM': 'Vietnam', 'YEM': 'Yemen', 'ZMB': 'Zambia', 'ZWE': 'Zimbabwe',
    // Portuguese-speaking Africa
    'STP': 'São Tomé and Príncipe',
  };

  static const Map<String, String> _alpha2ToName = {
    'AF': 'Afghanistan',
    'AL': 'Albania',
    'DZ': 'Algeria',
    'AO': 'Angola',
    'AR': 'Argentina',
    'AM': 'Armenia',
    'AU': 'Australia',
    'AT': 'Austria',
    'AZ': 'Azerbaijan',
    'BE': 'Belgium',
    'BR': 'Brazil',
    'BG': 'Bulgaria',
    'CA': 'Canada',
    'CL': 'Chile',
    'CN': 'China',
    'CO': 'Colombia',
    'HR': 'Croatia',
    'CY': 'Cyprus',
    'CZ': 'Czech Republic',
    'DK': 'Denmark',
    'EC': 'Ecuador',
    'EG': 'Egypt',
    'EE': 'Estonia',
    'FI': 'Finland',
    'FR': 'France',
    'DE': 'Germany',
    'GH': 'Ghana',
    'GR': 'Greece',
    'HN': 'Honduras',
    'HU': 'Hungary',
    'IN': 'India',
    'ID': 'Indonesia',
    'IR': 'Iran',
    'IQ': 'Iraq',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IT': 'Italy',
    'JP': 'Japan',
    'JO': 'Jordan',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'LV': 'Latvia',
    'LB': 'Lebanon',
    'LY': 'Libya',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'MY': 'Malaysia',
    'MX': 'Mexico',
    'MA': 'Morocco',
    'MZ': 'Mozambique',
    'NL': 'Netherlands',
    'NZ': 'New Zealand',
    'NG': 'Nigeria',
    'NO': 'Norway',
    'PA': 'Panama',
    'PK': 'Pakistan',
    'PE': 'Peru',
    'PH': 'Philippines',
    'PL': 'Poland',
    'PT': 'Portugal',
    'RO': 'Romania',
    'RU': 'Russia',
    'SA': 'Saudi Arabia',
    'SN': 'Senegal',
    'RS': 'Serbia',
    'ZA': 'South Africa',
    'ES': 'Spain',
    'LK': 'Sri Lanka',
    'SD': 'Sudan',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'SY': 'Syria',
    'TZ': 'Tanzania',
    'TH': 'Thailand',
    'TN': 'Tunisia',
    'TR': 'Turkey',
    'UA': 'Ukraine',
    'AE': 'United Arab Emirates',
    'GB': 'United Kingdom',
    'US': 'United States',
    'UY': 'Uruguay',
    'VE': 'Venezuela',
    'VN': 'Vietnam',
    'YE': 'Yemen',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
    'CV': 'Cape Verde',
    'ST': 'São Tomé and Príncipe',
  };
}
